name: ci
on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  TERM: xterm
  GO_VERSION: 1.22.6

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: "0"

      - name: ci/setup-go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache: true

      - name: ci/setup-node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: |
            webapp/package-lock.json
            e2e-tests/package-lock.json

      - name: ci/cache-node-modules
        id: cache-node-modules
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            webapp/node_modules
            e2e-tests/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('webapp/package-lock.json') }}-${{ hashFiles('e2e-tests/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules-${{ hashFiles('webapp/package-lock.json') }}-${{ hashFiles('e2e-tests/package-lock.json') }}

      - name: ci/setup-webapp-npm-deps
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        env:
          NODE_ENV: development
        run: |
          cd webapp
          npm install --ignore-scripts --no-save --legacy-peer-deps

      #- name: ci/setup-e2e-npm-deps
      #  if: steps.cache-node-modules.outputs.cache-hit != 'true'
      #  env:
      #    NODE_ENV: development
      #  run: |
      #    cd e2e-tests
      #    npm install --ignore-scripts --no-save

      - name: ci/go-tidy
        run: go mod tidy -v

      - name: ci/check-diff-on-gomod
        run: git --no-pager diff --exit-code go.mod go.sum || (echo "Please run \"go mod tidy\" and commit the changes in go.mod and go.sum." && exit 1)

      - name: ci/run-make-apply
        run: make apply

      - name: ci/check-diff-on-generated-manifest-files
        run: git --no-pager diff --exit-code *manifest.* || (echo "Please run \"make apply\" and commit the changes in the generated manifests." && exit 1)

      - name: ci/run-make-i18n-extract-webapp
        run: make i18n-extract-webapp

      - name: ci/check-diff-on-webapp-i18n-files
        run: git --no-pager diff --exit-code webapp/i18n/en.json || (echo "Please run \"make i18n-extract\" and commit the changes in webapp/i18n/en.json." && exit 1)

      - name: ci/run-make-graphql
        run: make graphql

      - name: ci/check-diff-on-webapp-graphql-generated-files
        run: git --no-pager diff --exit-code webapp/src/graphql/generated/ || (echo "Please run \"make graphql\" and commit the changes." && exit 1)

  dist:
    runs-on: ubuntu-22.04
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: "0"

      - name: ci/setup-go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache: true

      - name: ci/ensure-build-on-all-platforms
        run: make dist

  

  generate-specs:
    runs-on: ubuntu-22.04
    outputs:
      specs: ${{ steps.generate-specs.outputs.specs }}
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: ci/generate-specs
        id: generate-specs
        uses: ./.github/actions/generate-specs
        with:
          parallelism: 3
          directory: e2e-tests
          search_path: tests/integration

 
  